image: docker.vokal.io/python:2.7
env:
        - AWS_ACCESS_KEY=$$awsAccessKey
        - AWS_SECRET_KEY=$$awsSecretKey
        - STAGING_DATABASE_URL=$$stagingDatabaseUrl
        - DATABASE_URL=postgres://postgres@localhost
        - SECRET_KEY=$$secretKey
        - WEB_DOMAIN=$$webDomain

script:
    - apt-get update -qq && apt-get -y -qq install wget sudo
    - /bin/true

publish:
    docker:
        docker_host: tcp://docker-build.vokal.io:2375
        docker_version: 1.4.1
        registry_login_url: https://docker.vokal.io/v1/
        registry_login: true
        username: $$dockerUsername
        password: $$dockerPassword
        email: scott.ferguson@vokalinteractive.com
        image_name: docker.vokal.io/tf2stats
        tags: [latest]

deploy:
  bash:
      script:
        - fab staging update

notify:
    webhook:
        urls:
            - https://dronebot.vokal.io/hook
        on_success: true
        on_failure: true
